{% set version = "14.0.0.dev55c71c9eac9b" %}
{% set major_ver = version.split(".")[0] %}
{% set git_commit = "55c71c9eac9bc7f956a05fa9258fad4f86565450" %}
{% if git_commit != "" %}
  {% set archive_file = git_commit %}
{% else %}
  {% set archive_file = "refs/tags/llvmorg-" + version.replace(".rc", "-rc") %}
{% endif %}

package:
  name: mlir-split
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/archive/{{ archive_file }}.tar.gz
    sha256: 1459d328ea67802f5b7c64349ba300b5ddc4a78838d6b77a8a970fe99ed3e78c
    patches:
      # https://reviews.llvm.org/D99470
      - 0001-Support-cross-compiling-standalone-MLIR.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - llvmdev {{ version }}  # [build_platform != target_platform]
  host:
    - llvmdev {{ version }}
    - llvm {{ version }}
    - zlib

outputs:
  - name: mlir
    script: install_mlir.sh  # [unix]
    script: install_mlir.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - llvmdev {{ version }}    # [build_platform != target_platform]
      host:
        - {{ pin_subpackage("libmlir", exact=True) }}
        - llvmdev {{ version }}
        - llvm {{ version }}
        - zlib
      run:
        - {{ pin_subpackage("libmlir", exact=True) }}
        - llvmdev {{ version }}
    test:
      commands:
        - test -f "$PREFIX/include/mlir-c/Support.h"               # [unix]
        - test -f "$PREFIX/lib/libMLIRIR.a"                        # [unix]
        - if not exist %LIBRARY_INC%\\mlir-c\\Support.h exit 1     # [win]
        - if not exist %LIBRARY_LIB%\\MLIRIR.lib exit 1            # [win]
        - $PREFIX/bin/mlir-opt -version                            # [not win]
        - if not exist "%LIBRARY_BIN%"\\mlir-opt.exe exit 1        # [win]
        - mlir-opt -version                                        # [win]
        - mlir-tblgen -version

  - name: libmlir{{ major_ver }}
    script: install_libmlir.sh  # [unix]
    build:
      run_exports:
        - {{ pin_subpackage("libmlir" + major_ver, max_pin="x.x") }}   # [unix]
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - llvmdev {{ version }}    # [build_platform != target_platform]
      host:
        - llvmdev {{ version }}
        - llvm {{ version }}
        - zlib
    test:
      commands:
        - test ! -f "$PREFIX/lib/libMLIR$SHLIB_EXT"                                # [unix]
        - test ! -f "$PREFIX/lib/libmlir_runner_utils$SHLIB_EXT"                   # [unix]
        - test ! -f "$PREFIX/lib/libmlir_c_runner_utils$SHLIB_EXT"                 # [unix]
        - test ! -f "$PREFIX/lib/libmlir_c_runner_utils_static.a"                  # [unix]
        {% if git_commit != "" %}
        - test -f "$PREFIX/lib/libMLIR.so.{{ major_ver }}git"                     # [linux]
        - test -f "$PREFIX/lib/libmlir_runner_utils.so.{{ major_ver }}git"        # [linux]
        - test -f "$PREFIX/lib/libmlir_c_runner_utils.so.{{ major_ver }}git"      # [linux]
        - test -f "$PREFIX/lib/libMLIR.{{ major_ver }}git.dylib"                  # [osx]
        - test -f "$PREFIX/lib/libmlir_runner_utils.{{ major_ver }}git.dylib"     # [osx]
        - test -f "$PREFIX/lib/libmlir_c_runner_utils.{{ major_ver }}git.dylib"   # [osx]
        {% else %}
        - test -f "$PREFIX/lib/libMLIR.so.{{ major_ver }}"                     # [linux]
        - test -f "$PREFIX/lib/libmlir_runner_utils.so.{{ major_ver }}"        # [linux]
        - test -f "$PREFIX/lib/libmlir_c_runner_utils.so.{{ major_ver }}"      # [linux]
        - test -f "$PREFIX/lib/libMLIR.{{ major_ver }}.dylib"                  # [osx]
        - test -f "$PREFIX/lib/libmlir_runner_utils.{{ major_ver }}.dylib"     # [osx]
        - test -f "$PREFIX/lib/libmlir_c_runner_utils.{{ major_ver }}.dylib"   # [osx]
        {% endif %}

  - name: libmlir
    script: install_libmlir.sh  # [unix]
    build:
      {% if not win %}
      run_exports:   # [unix]
        - {{ pin_subpackage("libmlir" + major_ver, max_pin="x.x") }}   # [unix]
      {% endif %}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - llvmdev {{ version }}    # [build_platform != target_platform]
      host:
        - llvmdev {{ version }}
        - llvm {{ version }}
        - zlib
        - {{ pin_subpackage("libmlir" + major_ver, exact=True) }}  # [unix]
      run:
        - {{ pin_subpackage("libmlir" + major_ver, exact=True) }}  # [unix]
    test:
      commands:
        - test -f "$PREFIX/lib/libMLIR${SHLIB_EXT}"            # [unix]
        - if exist %LIBRARY_BIN%\\libmlir.dll exit 1           # [win]

about:
  home: http://llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: mlir/LICENSE.TXT
  license_family: Apache
  summary: Multi-Level IR Compiler Framework

extra:
  recipe-maintainers:
    - isuruf
    - kaushikcfd
    - xhochy
  feedstock-name: mlir
