{% set version = "18.1.1" %}
{% set major_version = version.split(".")[0] %}

# as of LLVM 17, we expect an "rc" suffix for the release candidates
{% set extra = "rc" if version.split(".")[-1]|int not in range(7) else "" %}
{% set extra = "git" if version.split(".")[-1] == "dev0" else extra %}

package:
  name: mlir-split
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
    sha256: 8f34c6206be84b186b4b31f47e1b52758fa38348565953fad453d177ef34c0ad
    patches:
      # https://reviews.llvm.org/D99470
      - patches/0001-Support-cross-compiling-standalone-MLIR.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - llvmdev {{ version }}  # [build_platform != target_platform]
    - zlib                   # [build_platform != target_platform]
  host:
    - llvmdev {{ version }}
    - llvm {{ version }}
    - zlib

outputs:
  - name: mlir
    script: install_mlir.sh  # [unix]
    script: install_mlir.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - llvmdev {{ version }}    # [build_platform != target_platform]
      host:
        - {{ pin_subpackage("libmlir", exact=True) }}
        - llvmdev {{ version }}
        - llvm {{ version }}
        - zlib
      run:
        - {{ pin_subpackage("libmlir", exact=True) }}
        - llvmdev {{ version }}
    test:
      commands:
        # static library
        - test -f $PREFIX/lib/libMLIRIR.a                       # [unix]
        - if not exist %LIBRARY_LIB%\MLIRIR.lib exit 1          # [win]

        # headers
        - test -f $PREFIX/include/mlir-c/Support.h              # [unix]
        - if not exist %LIBRARY_INC%\mlir-c\Support.h exit 1    # [win]

        # binaries
        - mlir-tblgen -version
        - $PREFIX/bin/mlir-opt -version                         # [unix]
        - if not exist "%LIBRARY_BIN%"\mlir-opt.exe exit 1      # [win]
        - mlir-opt -version                                     # [win]

  - name: libmlir{{ major_version }}
    script: install_libmlir.sh  # [unix]
    build:
      run_exports:
        - {{ pin_subpackage("libmlir" ~ major_version, max_pin="x.x") }}   # [unix]
      skip: true  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - llvmdev {{ version }}    # [build_platform != target_platform]
      host:
        - llvmdev {{ version }}
        - llvm {{ version }}
        - zlib
    test:
      commands:
        # presence of versioned libraries
        - test -f $PREFIX/lib/libMLIR.so.{{ major_version }}{{ extra }}                     # [linux]
        - test -f $PREFIX/lib/libmlir_runner_utils.so.{{ major_version }}{{ extra }}        # [linux]
        - test -f $PREFIX/lib/libmlir_c_runner_utils.so.{{ major_version }}{{ extra }}      # [linux]
        - test -f $PREFIX/lib/libMLIR.{{ major_version }}{{ extra }}.dylib                  # [osx]
        - test -f $PREFIX/lib/libmlir_runner_utils.{{ major_version }}{{ extra }}.dylib     # [osx]
        - test -f $PREFIX/lib/libmlir_c_runner_utils.{{ major_version }}{{ extra }}.dylib   # [osx]

        # absence of unversioned libraries
        - test ! -f $PREFIX/lib/libMLIR$SHLIB_EXT                   # [unix]
        - test ! -f $PREFIX/lib/libmlir_runner_utils$SHLIB_EXT      # [unix]
        - test ! -f $PREFIX/lib/libmlir_c_runner_utils$SHLIB_EXT    # [unix]
        - test ! -f $PREFIX/lib/libmlir_c_runner_utils_static.a     # [unix]

  - name: libmlir
    script: install_libmlir.sh  # [unix]
    build:
      {% if not win %}
      run_exports:   # [unix]
        - {{ pin_subpackage("libmlir" ~ major_version, max_pin="x.x") }}   # [unix]
      {% endif %}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - llvmdev {{ version }}    # [build_platform != target_platform]
      host:
        - llvmdev {{ version }}
        - llvm {{ version }}
        - zlib
        - {{ pin_subpackage("libmlir" ~ major_version, exact=True) }}  # [unix]
      run:
        - {{ pin_subpackage("libmlir" ~ major_version, exact=True) }}  # [unix]
    test:
      commands:
        # presence of unversioned libraries
        - test -f $PREFIX/lib/libMLIR${SHLIB_EXT}       # [unix]
        - if exist %LIBRARY_BIN%\libmlir.dll exit 1     # [win]

about:
  home: http://llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: mlir/LICENSE.TXT
  license_family: Apache
  summary: Multi-Level IR Compiler Framework

extra:
  recipe-maintainers:
    - h-vetinari
    - isuruf
    - kaushikcfd
    - xhochy
  feedstock-name: mlir
